import {
  defineNuxtModule,
  createResolver,
  logger,
  addImportsDir,
  addPlugin,
  addServerHandler,
  addRouteMiddleware,
  addTemplate,
} from "@nuxt/kit";
import defu from "defu";
import { z, type ZodType } from "zod";
import type { LocalAuthInitializerOptions } from "./runtime/providers/LocalAuthProvider";
import type { GithubAuthInitializerOptions } from "./runtime/providers/GithubAuthProvider";
import type { GoogleAuthInitializerOptions } from "./runtime/providers/GoogleAuthProvider";
export type { LocalAuthProvider } from "./runtime/providers/LocalAuthProvider";
export {
  AuthProvider,
  type AccessTokens,
  type AccessTokensNames,
  type AuthProviderContructorOptions,
} from "./runtime/providers/AuthProvider";
// export type { AuthPlugin } from "./runtime/plugin/auth";
export type { AuthState, AuthUser } from "./runtime/models";

export type ModuleProvidersOptions = {
  local?: LocalAuthInitializerOptions;
  github?: GithubAuthInitializerOptions;
  google?: GoogleAuthInitializerOptions;
  // [key: string]: AuthProviderInterface
};

export type DeepRequired<T> = Required<{
  [P in keyof T]: T[P] extends object | undefined
    ? DeepRequired<Required<T[P]>>
    : T[P];
}>;

export interface ModuleOptions {
  global: boolean;
  providers: ModuleProvidersOptions;
  defaultProvider?: string;
  redirects: {
    redirectIfNotLoggedIn?: string;
    redirectIfLoggedIn?: string;
  };
  apiClient: {
    baseURL: string;
  };
  token: {
    type: string;
    maxAge: number;
    cookiesNames: {
      accessToken: string;
      refreshToken: string;
      authProvider: string;
      tokenType: string;
    };
  };
}

type SchemaKind = "login" | "user";
type ProviderName = "local" | "github" | "google";

function zodToJson(
  provider: ProviderName,
  kind: SchemaKind,
  schema: ZodType,
): Record<string, unknown> {
  try {
    return z.toJSONSchema(schema) as Record<string, unknown>;
  } catch (e: any) {
    throw new Error(
      `@workmate/nuxt-auth: schema for ${provider}.${kind} cannot be represented as JSON Schema: ${e?.message ?? e}`,
    );
  }
}

function collectSchemas(providers: ModuleProvidersOptions): {
  login: Partial<Record<ProviderName, Record<string, unknown>>>;
  user: Partial<Record<ProviderName, Record<string, unknown>>>;
} {
  const login: Partial<Record<ProviderName, Record<string, unknown>>> = {};
  const user: Partial<Record<ProviderName, Record<string, unknown>>> = {};

  for (const name of ["local", "github", "google"] as const) {
    const cfg = providers[name];

    if (!cfg?.schemas) continue;

    if (cfg.schemas.login)
      login[name] = zodToJson(name, "login", cfg.schemas.login);

    if (cfg.schemas.user)
      user[name] = zodToJson(name, "user", cfg.schemas.user);
  }

  return { login, user };
}

function stripSchemasFromProviders(
  providers: ModuleProvidersOptions,
): ModuleProvidersOptions {
  const out: Record<string, unknown> = {};

  for (const name of ["local", "github", "google"] as const) {
    const cfg = providers[name];
    if (!cfg) continue;

    const { schemas: _schemas, ...rest } = cfg as Record<string, unknown> & {
      schemas?: unknown;
    };

    out[name] = rest;
  }

  return out as ModuleProvidersOptions;
}

function renderAuthSchemasTemplate(args: {
  login: Partial<Record<ProviderName, Record<string, unknown>>>;
  user: Partial<Record<ProviderName, Record<string, unknown>>>;
}): string {
  const loginJson = JSON.stringify(args.login, null, 2);
  const userJson = JSON.stringify(args.user, null, 2);

  return `// AUTO-GENERATED by @workmate/nuxt-auth — do not edit.
import { z } from "zod";

const loginJsonSchemas: Record<string, any> = ${loginJson};
const userJsonSchemas: Record<string, any> = ${userJson};

function build(map: Record<string, any>) {
  const out: Record<string, z.ZodType | undefined> = {};
  for (const key of ["local", "github", "google"]) {
    out[key] = map[key] ? z.fromJSONSchema(map[key]) : undefined;
  }
  return out as { local?: z.ZodType; github?: z.ZodType; google?: z.ZodType };
}

export const loginSchemas = build(loginJsonSchemas);
export const userSchemas = build(userJsonSchemas);

type InferOr<T, F> = [T] extends [z.ZodType] ? z.infer<T> : F;

export type LoginData = {
  local: InferOr<NonNullable<typeof loginSchemas.local>, Record<string, any>>;
  github: { redirectUrl?: string };
  google: { redirectUrl?: string };
};

export type UserDataByProvider = {
  local: InferOr<NonNullable<typeof userSchemas.local>, Record<string, any>>;
  github: InferOr<NonNullable<typeof userSchemas.github>, Record<string, any>>;
  google: InferOr<NonNullable<typeof userSchemas.google>, Record<string, any>>;
};
`;
}

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: "@workmate/nuxt-auth",
    configKey: "auth",
    compatibility: {
      nuxt: ">=3.0.0",
    },
  },
  defaults: {
    global: false,
    providers: {},
    redirects: {
      redirectIfNotLoggedIn: "/login",
      redirectIfLoggedIn: "/",
    },
    apiClient: {
      baseURL: "",
    },
    defaultProvider: "local",
    token: {
      type: "Bearer",
      maxAge: 1000 * 60 * 60 * 24 * 30,
      cookiesNames: {
        accessToken: "auth:token",
        refreshToken: "auth:refreshToken",
        authProvider: "auth:provider",
        tokenType: "auth:tokenType",
      },
    },
  },
  async setup(options, nuxt) {
    logger.log("@workmate/nuxt-auth:: installing module");
    const resolver = createResolver(import.meta.url);

    const collected = collectSchemas(options.providers);

    const template = addTemplate({
      filename: "auth-schemas.gen.ts",
      write: true,
      getContents: () => renderAuthSchemasTemplate(collected),
    });

    nuxt.options.alias = nuxt.options.alias || {};
    nuxt.options.alias["#auth-schemas"] = template.dst;
    nuxt.options.nitro = nuxt.options.nitro || {};
    nuxt.options.nitro.alias = nuxt.options.nitro.alias || {};
    nuxt.options.nitro.alias["#auth-schemas"] = template.dst;

    const serializableOptions: ModuleOptions = {
      ...options,
      providers: stripSchemasFromProviders(options.providers),
    };

    nuxt.options.runtimeConfig.auth = defu(
      nuxt.options.runtimeConfig.auth,
      serializableOptions,
    ) as ModuleOptions;

    nuxt.options.runtimeConfig.public.auth = defu(
      nuxt.options.runtimeConfig.public.auth,
      {
        redirects: options.redirects,
        global: options.global,
        apiClient: options.apiClient,
      },
    );

    addImportsDir(resolver.resolve("runtime/composables"));
    addPlugin(resolver.resolve("./runtime/plugin/auth"));
    addPlugin(resolver.resolve("./runtime/plugin/auth-fetch"), {
      append: true,
    });

    addServerHandler({
      middleware: true,
      handler: resolver.resolve("./runtime/server/middleware/auth"),
    });

    addServerHandler({
      route: "/api/auth/login",
      handler: resolver.resolve("./runtime/server/api/login.post"),
    });

    addServerHandler({
      route: "/api/auth/logout",
      handler: resolver.resolve("./runtime/server/api/logout.post"),
    });

    addServerHandler({
      route: "/api/auth/user",
      handler: resolver.resolve("./runtime/server/api/user"),
    });

    addServerHandler({
      route: "/api/auth/refresh",
      handler: resolver.resolve("./runtime/server/api/refresh.post"),
    });

    if (nuxt.options.runtimeConfig.auth.providers.github) {
      addServerHandler({
        route: "/api/auth/callback/github",
        handler: resolver.resolve("./runtime/server/api/callback/github.get"),
      });
    }

    if (nuxt.options.runtimeConfig.auth.providers.google) {
      addServerHandler({
        route: "/api/auth/callback/google",
        handler: resolver.resolve("./runtime/server/api/callback/google.get"),
      });
    }
    addRouteMiddleware({
      name: "auth",
      path: resolver.resolve("./runtime/middleware/auth"),
    });

    addRouteMiddleware({
      name: "auth-guest",
      path: resolver.resolve("./runtime/middleware/auth-guest"),
    });

    if (nuxt.options.runtimeConfig.auth.global) {
      addRouteMiddleware({
        name: "auth-global",
        path: resolver.resolve("./runtime/middleware/auth.global"),
        global: true,
      });
    }

    logger.success("@workmate/nuxt-auth:: successfully installed");
  },
});

declare module "@nuxt/schema" {
  interface RuntimeConfig {
    auth: ModuleOptions;
  }

  interface PublicRuntimeConfig {
    auth: {
      redirects: ModuleOptions["redirects"];
      global: ModuleOptions["global"];
      apiClient: ModuleOptions["apiClient"];
    };
  }
}
