import { z, type ZodType } from "zod";
import type { LocalAuthInitializerOptions } from "./runtime/providers/LocalAuthProvider";
import type { GithubAuthInitializerOptions } from "./runtime/providers/GithubAuthProvider";
import type { GoogleAuthInitializerOptions } from "./runtime/providers/GoogleAuthProvider";

export type ProviderName = "local" | "github" | "google";
type SchemaKind = "login" | "user";

export type ModuleProvidersOptions = {
  local?: LocalAuthInitializerOptions;
  github?: GithubAuthInitializerOptions;
  google?: GoogleAuthInitializerOptions;
};

export type CollectedSchemas = {
  login: Partial<Record<ProviderName, Record<string, unknown>>>;
  user: Partial<Record<ProviderName, Record<string, unknown>>>;
};

function zodToJson(
  provider: ProviderName,
  kind: SchemaKind,
  schema: ZodType,
): Record<string, unknown> {
  try {
    return z.toJSONSchema(schema) as Record<string, unknown>;
  } catch (e: any) {
    throw new Error(
      `@workmate/nuxt-auth: schema for ${provider}.${kind} cannot be represented as JSON Schema: ${e?.message ?? e}`,
    );
  }
}

export function collectSchemas(
  providers: ModuleProvidersOptions,
): CollectedSchemas {
  const login: Partial<Record<ProviderName, Record<string, unknown>>> = {};
  const user: Partial<Record<ProviderName, Record<string, unknown>>> = {};

  for (const name of ["local", "github", "google"] as const) {
    const cfg = providers[name];

    if (!cfg?.schemas) continue;

    if (cfg.schemas.login)
      login[name] = zodToJson(name, "login", cfg.schemas.login);

    if (cfg.schemas.user)
      user[name] = zodToJson(name, "user", cfg.schemas.user);
  }

  return { login, user };
}

export function stripSchemasFromProviders(
  providers: ModuleProvidersOptions,
): ModuleProvidersOptions {
  const out: Record<string, unknown> = {};

  for (const name of ["local", "github", "google"] as const) {
    const cfg = providers[name];
    if (!cfg) continue;

    const { schemas: _schemas, ...rest } = cfg as Record<string, unknown> & {
      schemas?: unknown;
    };

    out[name] = rest;
  }

  return out as ModuleProvidersOptions;
}

export function renderAuthSchemasRuntime(args: CollectedSchemas): string {
  const loginJson = JSON.stringify(args.login, null, 2);
  const userJson = JSON.stringify(args.user, null, 2);

  return `// AUTO-GENERATED by @workmate/nuxt-auth — do not edit.
import { z } from "zod";

const loginJsonSchemas = ${loginJson};
const userJsonSchemas = ${userJson};

function build(map) {
  const out = {};
  for (const key of ["local", "github", "google"]) {
    out[key] = map[key] ? z.fromJSONSchema(map[key]) : undefined;
  }
  return out;
}

export const loginSchemas = build(loginJsonSchemas);
export const userSchemas = build(userJsonSchemas);
`;
}

function jsonSchemaToTsType(
  schema: Record<string, unknown> | undefined,
): string {
  if (!schema) return "Record<string, any>";

  if (schema.type === "object") {
    const props =
      (schema.properties as Record<string, Record<string, unknown>>) ?? {};

    const required = (schema.required as string[]) ?? [];

    const fields = Object.entries(props).map(([key, val]) => {
      const opt = required.includes(key) ? "" : "?";
      return `${key}${opt}: ${jsonSchemaToTsType(val)}`;
    });

    return fields.length ? `{ ${fields.join("; ")} }` : "Record<string, any>";
  }

  if (schema.type === "string") return "string";
  if (schema.type === "number" || schema.type === "integer") return "number";
  if (schema.type === "boolean") return "boolean";
  if (schema.type === "null") return "null";

  if (schema.type === "array") {
    const items = schema.items as Record<string, unknown> | undefined;
    return `Array<${jsonSchemaToTsType(items)}>`;
  }

  const union = (schema.anyOf ?? schema.oneOf) as
    | Record<string, unknown>[]
    | undefined;

  if (union) return union.map(jsonSchemaToTsType).join(" | ");

  return "Record<string, any>";
}

export function renderAuthSchemasTypes(args: CollectedSchemas): string {
  const loginLocal = jsonSchemaToTsType(args.login.local);
  const userLocal = jsonSchemaToTsType(args.user.local);
  const userGithub = jsonSchemaToTsType(args.user.github);
  const userGoogle = jsonSchemaToTsType(args.user.google);

  return `// AUTO-GENERATED by @workmate/nuxt-auth — do not edit.

export type LoginData = {
  local: ${loginLocal};
  github: { redirectUrl?: string };
  google: { redirectUrl?: string };
};

export type UserDataByProvider = {
  local: ${userLocal};
  github: ${userGithub};
  google: ${userGoogle};
};
`;
}
